name: Build SunamoHttp

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoHttp
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoHttp/SunamoHttp.csproj

    - name: Build
      run: dotnet build SunamoHttp/SunamoHttp.csproj --configuration Release --no-restore

  test:
    name: Test SunamoHttp.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoHttp.Tests/SunamoHttp.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoHttp.Tests/SunamoHttp.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoHttp.Tests/SunamoHttp.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
